-- ÜBERHOLT – nicht mehr ausführen.
--
-- Die Rechte für Anlagendaten und offene Störungen regelt jetzt
-- tools/rollen.sql (Techniker dürfen Anlagen UND offene Störungen speichern,
-- Kunde und Präsentation nichts). Dieses alte Skript kannte die Störungen
-- und die Rollen noch nicht und hätte Technikern das zentrale Speichern
-- offener Störungen wieder genommen.
--
-- Wer es versehentlich ausgeführt hat: einfach tools/rollen.sql erneut
-- ausführen, das stellt die richtigen Regeln wieder her.
select 'überholt – bitte tools/rollen.sql verwenden' as hinweis;
